import { motion } from "framer-motion";
import { ArrowLeft, AlertTriangle, FileText } from "lucide-react";
import { useNavigate } from "react-router-dom";

const Terms = () => {
  const navigate = useNavigate();

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="min-h-screen px-4 py-8 max-w-lg mx-auto"
    >
      <button
        onClick={() => navigate(-1)}
        className="h-9 w-9 rounded-xl bg-card border border-border flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-primary/5 transition-colors active:scale-95 mb-6"
      >
        <ArrowLeft className="h-4 w-4" />
      </button>

      <div className="flex items-center gap-3 mb-6">
        <div className="h-10 w-10 rounded-full bg-primary/15 flex items-center justify-center">
          <FileText className="h-5 w-5 text-primary" />
        </div>
        <h1 className="font-display text-2xl font-bold text-foreground">Terms of Service</h1>
      </div>

      <p className="text-xs text-muted-foreground font-light mb-6">
        Last updated: March 2026
      </p>

      {/* Medical Disclaimer Banner */}
      <div className="rounded-xl border border-destructive/30 bg-destructive/8 p-4 mb-6">
        <div className="flex items-start gap-3">
          <AlertTriangle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
          <div className="space-y-2">
            <h2 className="font-display text-sm font-bold text-destructive">
              ⚠️ Important: Medical Disclaimer
            </h2>
            <p className="text-xs text-foreground font-light leading-relaxed">
              Circadia is an AI-powered informational tool, not a medical provider. The content generated by this app does not constitute professional medical advice, diagnosis, or treatment.
            </p>
          </div>
        </div>
      </div>

      <div className="space-y-6">
        <section className="rounded-xl border border-border bg-card/80 dreamy-blur p-4 space-y-2">
          <h2 className="font-display text-sm font-semibold text-foreground">Not Professional Advice</h2>
          <p className="text-xs text-muted-foreground font-light leading-relaxed">
            The nutrition plans generated are for educational purposes and are produced by artificial intelligence. They do not substitute for professional medical advice, diagnosis, or treatment. Always seek the guidance of a qualified health provider with any questions regarding your health.
          </p>
        </section>

        <section className="rounded-xl border border-border bg-card/80 dreamy-blur p-4 space-y-2">
          <h2 className="font-display text-sm font-semibold text-foreground">AI Accuracy</h2>
          <p className="text-xs text-muted-foreground font-light leading-relaxed">
            AI can produce inaccurate or incomplete nutritional values. Always verify ingredients, especially if you have allergies or underlying health conditions such as diabetes, heart disease, or other chronic conditions.
          </p>
        </section>

        <section className="rounded-xl border border-border bg-card/80 dreamy-blur p-4 space-y-2">
          <h2 className="font-display text-sm font-semibold text-foreground">Assumption of Risk</h2>
          <p className="text-xs text-muted-foreground font-light leading-relaxed">
            By using this app, you acknowledge that you are following these schedules at your own risk. Consult a doctor before making significant changes to your diet, especially when working high-stress night shifts.
          </p>
        </section>

        <section className="rounded-xl border border-border bg-card/80 dreamy-blur p-4 space-y-2">
          <h2 className="font-display text-sm font-semibold text-foreground">No Guarantees</h2>
          <p className="text-xs text-muted-foreground font-light leading-relaxed">
            We do not guarantee specific health outcomes, including but not limited to weight loss, improved sleep quality, or enhanced energy levels. Individual results may vary based on numerous factors beyond the scope of this application.
          </p>
        </section>
      </div>

      <p className="text-center text-[10px] text-muted-foreground/50 mt-8 mb-4 font-light">
        © 2026 Circadia. All rights reserved.
      </p>
    </motion.div>
  );
};

export default Terms;
