
ALTER TABLE public.water_intake_settings
  ADD COLUMN IF NOT EXISTS notify_hydration BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notify_meals BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notify_phases BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notify_tips BOOLEAN NOT NULL DEFAULT true;
